import {
  bigint,
  boolean,
  char,
  date,
  numeric,
  pgTable,
  text,
  timestamp,
  varchar,
} from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  id: bigint("id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity(),
  googleId: varchar("google_id", { length: 255 }).notNull(),
  email: varchar("email", { length: 255 }).notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }),
});

export const sessions = pgTable("sessions", {
  id: text("id").primaryKey(),
  userId: bigint("user_id", { mode: "number" })
    .notNull()
    .references(() => users.id),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
});

export const categories = pgTable("categories", {
  id: bigint("id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity(),
  userId: bigint("user_id", { mode: "number" }).references(() => users.id),
  name: varchar("name", { length: 255 }),
  type: char("type", { enum: ["INCOME", "EXPENSE"] }),
  isDefault: boolean("is_default"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }),
});

export const accounts = pgTable("accounts", {
  id: bigint("id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity(),
  userId: bigint("user_id", { mode: "number" }).references(() => users.id),
  name: varchar("name", { length: 255 }),
  balance: numeric("balance"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }),
});

// create table public.transactions (
//   id bigint generated by default as identity not null,
//   user_id bigint null,
//   account_id bigint null,
//   type character varying null,
//   amount numeric null default '0'::numeric,
//   description text null,
//   transaction_date date null,
//   created_at timestamp with time zone not null default now(),
//   updated_at timestamp without time zone null,
//   category_id bigint null,
//   constraint transactions_pkey primary key (id),
//   constraint transactions_category_id_fkey foreign KEY (category_id) references categories (id) on delete CASCADE,
//   constraint transactions_from_account_id_fkey foreign KEY (account_id) references accounts (id) on delete CASCADE,
//   constraint transactions_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE
// ) TABLESPACE pg_default;
//
export const transactions = pgTable("transactions", {
  id: bigint("id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity(),
  userId: bigint("user_id", { mode: "number" }).references(() => users.id),
  accountId: bigint("account_id", { mode: "number" }).references(
    () => accounts.id,
  ),
  categoryId: bigint("category_id", { mode: "number" }).references(
    () => categories.id,
  ),
  type: char("type", { enum: ["INCOME", "EXPENSE"] }),
  amount: numeric("amount"),
  description: text("description"),
  transaction_date: date("transaction_date"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }),
});
